server:
  port: 8081
springdoc:
  swagger-ui:
    path: swagger
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:fakedatadb
    driverClassName: org.h2.Driver
    username: user
    password: root